-- CreateTable
CREATE TABLE "Companies" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "symbol" TEXT NOT NULL,
    "ratingCategoryId" INTEGER NOT NULL,

    CONSTRAINT "Companies_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Quotes" (
    "id" SERIAL NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "currency" TEXT NOT NULL,
    "targetPriceHigh" INTEGER NOT NULL,
    "targetPriceLow" INTEGER NOT NULL,
    "targetPriceMean" INTEGER NOT NULL,
    "targetPriceMedian" INTEGER NOT NULL,
    "heldPercentInsiders" INTEGER NOT NULL,
    "heldPercentInstitutions" INTEGER NOT NULL,
    "regularMarketChange" INTEGER NOT NULL,
    "regularMarketChangePercent" INTEGER NOT NULL,
    "regularMarketTime" INTEGER NOT NULL,
    "regularMarketPrice" INTEGER NOT NULL,
    "regularMarketDayHigh" INTEGER NOT NULL,
    "regularMarketDayRange" TEXT NOT NULL,
    "regularMarketDayLow" INTEGER NOT NULL,
    "regularMarketVolume" INTEGER NOT NULL,
    "sharesShort" INTEGER NOT NULL,
    "sharesShortPrevMonth" INTEGER NOT NULL,
    "regularMarketPreviousClose" INTEGER NOT NULL,
    "bid" INTEGER NOT NULL,
    "ask" INTEGER NOT NULL,
    "bidSize" INTEGER NOT NULL,
    "askSize" INTEGER NOT NULL,
    "regularMarketOpen" INTEGER NOT NULL,
    "averageDailyVolume3Month" INTEGER NOT NULL,
    "averageDailyVolume10Day" INTEGER NOT NULL,
    "beta" INTEGER NOT NULL,
    "fiftyTwoWeekLowChange" INTEGER NOT NULL,
    "fiftyTwoWeekLowChangePercent" INTEGER NOT NULL,
    "fiftyTwoWeekRange" TEXT NOT NULL,
    "fiftyTwoWeekHighChange" INTEGER NOT NULL,
    "fiftyTwoWeekHighChangePercent" INTEGER NOT NULL,
    "fiftyTwoWeekLow" INTEGER NOT NULL,
    "fiftyTwoWeekHigh" INTEGER NOT NULL,
    "dividendDate" BIGINT NOT NULL,
    "earningsTimestamp" BIGINT NOT NULL,
    "earningsTimestampStart" BIGINT NOT NULL,
    "earningsTimestampEnd" BIGINT NOT NULL,
    "trailingAnnualDividendRate" INTEGER NOT NULL,
    "dividendsPerShare" INTEGER NOT NULL,
    "trailingAnnualDividendYield" INTEGER NOT NULL,
    "epsTrailingTwelveMonths" INTEGER NOT NULL,
    "sharesOutstanding" INTEGER NOT NULL,
    "bookValue" INTEGER NOT NULL,
    "fiftyDayAverage" INTEGER NOT NULL,
    "fiftyDayAverageChange" INTEGER NOT NULL,
    "fiftyDayAverageChangePercent" INTEGER NOT NULL,
    "twoHundredDayAverage" INTEGER NOT NULL,
    "twoHundredDayAverageChange" INTEGER NOT NULL,
    "twoHundredDayAverageChangePercent" INTEGER NOT NULL,
    "marketCap" BIGINT NOT NULL,
    "priceToBook" INTEGER NOT NULL,
    "sourceInterval" INTEGER NOT NULL,
    "gmtOffSetMilliseconds" INTEGER NOT NULL,
    "firstTradeDateMilliseconds" BIGINT NOT NULL,
    "priceHint" INTEGER NOT NULL,
    "totalCash" INTEGER NOT NULL,
    "floatShares" BIGINT NOT NULL,
    "ebitda" BIGINT NOT NULL,
    "shortRatio" INTEGER NOT NULL,

    CONSTRAINT "Quotes_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Companies" ADD CONSTRAINT "Companies_ratingCategoryId_fkey" FOREIGN KEY ("ratingCategoryId") REFERENCES "RatingCategories"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
